### ISSUE TITLE
建立安全连接失败

### ISSUE THREAD

**Issue by luckypoem** [gaowanliang/MagicPassword#2]
访问https://pwd.gwliang.com/zh-cn.html ，显示：
建立安全连接失败

连接到 pwd.gwliang.com 时发生错误。无法安全地与对等端通信：没有双方共用的加密算法。

错误代码：SSL_ERROR_NO_CYPHER_OVERLAP

    由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
    建议向此网站的管理员反馈这个问题。

证书过期了？请更新证书

**Comment by gaowanliang** [comment]
已更新证书
